# Generated by Django 6.0.3 on 2026-03-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.guideprofile', verbose_name='Гид')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_reports', to=settings.AUTH_USER_MODEL, verbose_name='Пожаловался')),
            ],
            options={
                'verbose_name': 'Жалоба на гида',
                'verbose_name_plural': 'Жалобы на гидов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200, verbose_name='Полное имя (по документу)')),
                ('display_name', models.CharField(max_length=150, verbose_name='Отображаемое имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('languages', models.CharField(help_text='Через запятую, напр: ru, en, de', max_length=200, verbose_name='Языки')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('service_types', models.TextField(blank=True, help_text='Какие экскурсии / услуги предлагаете', verbose_name='Типы услуг')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=10, verbose_name='Уровень риска')),
                ('id_document_image', models.ImageField(upload_to='verification/ids/', verbose_name='Документ (фото)')),
                ('selfie_image', models.ImageField(upload_to='verification/selfies/', verbose_name='Селфи')),
                ('agreed_to_safety_rules', models.BooleanField(default=False, verbose_name='Согласен с правилами безопасности')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('under_review', 'На рассмотрении'), ('approved_limited', 'Одобрена'), ('rejected', 'Отклонена'), ('suspended', 'Приостановлена')], default='draft', max_length=20, verbose_name='Статус')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Внутренние заметки (для админа)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to='accounts.guideprofile', verbose_name='Гид')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Заявка на верификацию',
                'verbose_name_plural': 'Заявки на верификацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
