# Generated by Django 6.0.3 on 2026-03-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Через запятую, напр: ru, en, de', max_length=200, verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='guides/photos/', verbose_name='Фото (портфолио)'),
        ),
        migrations.AlterField(
            model_name='touristprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
    ]
