# Generated by Django 6.0.3 on 2026-03-25 07:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_guideprofile_avatar_touristprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[accounts.models.validate_image_size], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='guides/photos/', validators=[accounts.models.validate_image_size], verbose_name='Фото (портфолио)'),
        ),
    ]
