# Generated by Django 6.0.3 on 2026-03-26 15:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(max_length=100, verbose_name='Город / район')),
                ('category', models.CharField(choices=[('walking', 'Пешая'), ('driving', 'На транспорте'), ('food', 'Гастро-тур'), ('adventure', 'Приключение'), ('culture', 'Культура'), ('nature', 'Природа'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2, max_digits=4, verbose_name='Длительность (часов)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена ($)')),
                ('mode', models.CharField(choices=[('private', 'Приватная'), ('group', 'Групповая')], default='private', max_length=10, verbose_name='Режим')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('meeting_point', models.CharField(blank=True, max_length=300, verbose_name='Место встречи')),
                ('max_participants', models.PositiveIntegerField(default=1, help_text='Для приватных = 1, для групповых > 1', verbose_name='Макс. участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.guideprofile', verbose_name='Гид')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_guests', models.PositiveIntegerField(default=1, verbose_name='Кол-во гостей')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='experiences.experience', verbose_name='Экскурсия')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Турист')),
            ],
            options={
                'verbose_name': 'Бронирование экскурсии',
                'verbose_name_plural': 'Бронирования экскурсий',
                'ordering': ['-created_at'],
                'unique_together': {('experience', 'tourist')},
            },
        ),
        migrations.CreateModel(
            name='ExperienceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='experiences.experiencebooking', verbose_name='Бронирование')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='experiences.experience', verbose_name='Экскурсия')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_reviews', to='accounts.guideprofile', verbose_name='Гид')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Турист')),
            ],
            options={
                'verbose_name': 'Отзыв на экскурсию',
                'verbose_name_plural': 'Отзывы на экскурсии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideFeedbackSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(verbose_name='Сводка')),
                ('source_review_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во отзывов')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Сгенерировано')),
                ('guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_summary', to='accounts.guideprofile', verbose_name='Гид')),
            ],
            options={
                'verbose_name': 'AI-сводка отзывов',
                'verbose_name_plural': 'AI-сводки отзывов',
            },
        ),
    ]
