# Generated by Django 6.0.3 on 2026-03-25 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_guideprofile_avatar_touristprofile_avatar_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('tourist', 'guide')},
        ),
    ]
