# Generated by Django 5.1.4 on 2026-03-24 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Текст запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requests', to=settings.AUTH_USER_MODEL, verbose_name='Турист')),
            ],
            options={
                'verbose_name': 'Запрос подбора',
                'verbose_name_plural': 'Запросы подбора',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Оценка совпадения')),
                ('reason', models.TextField(blank=True, verbose_name='Обоснование')),
                ('compromise', models.TextField(blank=True, verbose_name='Компромисс')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='accounts.guideprofile', verbose_name='Гид')),
                ('match_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='matching.matchrequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Результат подбора',
                'verbose_name_plural': 'Результаты подбора',
                'ordering': ['-score'],
            },
        ),
    ]
