# Generated by Django 6.0.3 on 2026-03-27 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_total', models.PositiveIntegerField(blank=True, null=True)),
                ('interests', models.TextField(blank=True)),
                ('pace', models.CharField(blank=True, max_length=30)),
                ('people_count', models.PositiveIntegerField(default=1)),
                ('with_children', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('collecting', 'Сбор данных'), ('ready', 'Маршрут готов')], default='collecting', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия чата AI',
                'verbose_name_plural': 'Сессии чата AI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'AI')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='matching.matchsession')),
            ],
            options={
                'verbose_name': 'Сообщение AI-чата',
                'verbose_name_plural': 'Сообщения AI-чата',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_result', models.JSONField(default=dict)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plan', to='matching.matchsession')),
            ],
            options={
                'verbose_name': 'Маршрут поездки',
                'verbose_name_plural': 'Маршруты поездок',
            },
        ),
    ]
